# Generated by Django 4.0.6 on 2025-06-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_branchstock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='importtax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
