# Generated by Django 4.0.6 on 2025-07-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_importtax_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='How much of the component is used to make 1 unit')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_boms', to='product.product')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='product.product')),
            ],
        ),
    ]
