# Generated by Django 4.0.6 on 2025-04-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_bill_is_end_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='excise_duty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
