# Generated by Django 4.0.6 on 2025-07-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0014_tablreturnentry_excise_duty_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
