# Generated by Django 4.0.6 on 2025-05-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchase_excise_duty_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpurchaseentry',
            name='purchase_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
