# Generated by Django 4.0.6 on 2025-05-26 11:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_tblpurchaseentry_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        # Optional: Update old values to have .00 decimal places explicitly
        migrations.RunSQL(
            sql="UPDATE purchase_productpurchase SET quantity = quantity * 1.00",
            reverse_sql="UPDATE purchase_productpurchase SET quantity = ROUND(quantity)"
        ),
    ]
