# Generated by Django 4.0.6 on 2025-06-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_alter_productpurchase_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetpurchaseitem',
            name='quantity',
        ),
    ]
