# Generated by Django 4.0.6 on 2025-06-03 07:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_remove_assetpurchaseitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpurchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
