# Generated by Django 4.0.6 on 2025-06-04 08:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_importtax_percent'),
        ('purchase', '0009_assetpurchaseitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('item_total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('importtax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tblpurchaseentry',
            name='import_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasereturn',
            name='import_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ImportPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('bill_date', models.DateField()),
                ('bill_no', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('non_taxable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('amount_in_words', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(max_length=30)),
                ('excise_duty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('import_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('products', models.ManyToManyField(through='purchase.ImportProductPurchase', to='product.product')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='importproductpurchase',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.importpurchase'),
        ),
    ]
