# Generated by Django 4.0.6 on 2025-07-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_importproductpurchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpurchaseentry',
            name='taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasereturn',
            name='taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
