# Generated by Django 4.0.6 on 2025-07-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_tbljournalentry_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativeledger',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
